version: '3.7'

services:

  coinbase-vwap:
    build: .
    image: flaviostutz/coinbase-vwap
    environment:
      - LOG_LEVEL=debug
      # - COINBASE_WS_URL=

#   zookeeper:
#     image: wurstmeister/zookeeper
#     ports:
#       - "2181:2181"
#   kafka:
#     build: .
#     ports:
#       - "9092:9092"
#     environment:
#       KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#       KAFKA_CREATE_TOPICS: "test:1:1"
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock